#!/usr/bin/env python3
"""Generate versioned manuscript statistics and LaTeX release tables."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from physiomap_core.quantitative_validation import validate_quantitative_manifest
from physiomap_core.scm import ScmManifest

ROOT = Path(__file__).resolve().parent.parent


def table(headers: list[str], rows: list[list[object]], alignment: str | None = None) -> str:
    alignment = alignment or ("l" + "r" * (len(headers) - 1))
    body = ["% Generated by scripts/generate_migration_statistics.py; do not edit.",
            f"\\begin{{tabular}}{{{alignment}}}", "\\hline",
            " & ".join(headers) + " \\\\", "\\hline"]
    body.extend(" & ".join(str(value) for value in row) + " \\\\" for row in rows)
    body.extend(["\\hline", "\\end{tabular}"])
    return "\n".join(body) + "\n"


def render(artifact_dir: Path) -> dict[str, str]:
    scm = ScmManifest.from_json(artifact_dir / "physiomap-scm.json")
    report = json.loads((artifact_dir / "migration-report.json").read_text(encoding="utf-8"))
    golden = json.loads((ROOT / "benchmarks/golden/owl-scm-v2.json").read_text(encoding="utf-8"))
    modules = json.loads((ROOT / "ontology/modules/manifest.json").read_text(encoding="utf-8"))
    evidence_review = json.loads(
        (ROOT / "docs/generated/legacy-evidence-worklist.json").read_text(encoding="utf-8"))
    quantitative = validate_quantitative_manifest(scm)
    expression_kinds = Counter(expression.kind for expression in scm.quantitative_expressions)
    projection_counts = scm.ontology_provenance["projection_entailments"]["counts"]
    summary = report["summary"]
    stats = {
        "schema_version": "1.0.0", "physiomap_version": scm.physiomap_version,
        "projection_version": scm.projection_version, "generator_version": scm.generator_version,
        "traits": len(scm.nodes), "complete_traits": summary["complete_traits"],
        "incomplete_traits": summary["incomplete_traits"], "influences": len(scm.influences),
        "production_relations": len(scm.production_relations),
        "constitutive_constraints": len(scm.constitutive_constraints),
        "quantitative_expressions": len(scm.quantitative_expressions),
        "quantitative_expression_kinds": dict(sorted(expression_kinds.items())),
        "modulations": len(scm.modulation), "projection_traces": len(scm.projection_traces),
        "unique_elk_entailments": sum(projection_counts.values()),
        "projection_pattern_counts": projection_counts,
        "derivative_rules_checked": quantitative.exact_rules_checked,
        "numerical_realization_trials": quantitative.numerical_trials,
        "source_modules": modules["modules"], "ontology_checksums": scm.ontology_provenance["checksums"],
        "benchmarks": golden["benchmarks"], "hpo": golden["hpo"], "graph": golden["graph"],
        "reasoning_validation": report["reasoning_validation"],
        "causal_evidence": {
            "controlled": sum(edge.evidence_status == "controlled" for edge in scm.influences),
            "legacy_unclassified": sum(edge.evidence_status == "legacy-evidence-unclassified"
                                       for edge in scm.influences),
            "review_baseline": evidence_review["summary"]["baseline_total"],
            "review_open": evidence_review["summary"]["open"],
            "review_approved_resolved": evidence_review["summary"]["approved_resolved"],
        },
        "production_evidence": {
            "controlled": sum(edge.evidence_status == "controlled"
                              for edge in scm.production_relations),
            "legacy_unclassified": sum(
                edge.evidence_status == "legacy-evidence-unclassified"
                for edge in scm.production_relations
            ),
        },
    }
    outputs = {"statistics.json": json.dumps(stats, indent=2, sort_keys=True) + "\n"}
    outputs["ontology-composition.tex"] = table(["Artifact", "Count"], [
        ["Traits", stats["traits"]], ["Complete contextual traits", stats["complete_traits"]],
        ["Incomplete primitive traits", stats["incomplete_traits"]],
        ["Projected influences", stats["influences"]],
        ["Production relations", stats["production_relations"]],
        ["Constitutive constraints", stats["constitutive_constraints"]],
        ["Quantitative expressions", stats["quantitative_expressions"]],
        ["Modulations", stats["modulations"]], ["Projection traces", stats["projection_traces"]]])
    outputs["trait-completeness.tex"] = table(["Trait status", "Count", "Percent"], [
        ["Complete", stats["complete_traits"], f"{100*stats['complete_traits']/stats['traits']:.1f}\\%"],
        ["Incomplete primitive", stats["incomplete_traits"],
         f"{100*stats['incomplete_traits']/stats['traits']:.1f}\\%"]])
    outputs["projection-patterns.tex"] = table(["Pattern", "Unique entailments"], [
        [name.replace("-", "\\mbox{-}"), count] for name, count in sorted(projection_counts.items())])
    outputs["legacy-recovery.tex"] = table(["Migration check", "Recovered", "Expected"], [
        ["Nodes", len(scm.nodes), golden["model"]["nodes"]["count"]],
        ["Contextual influences", len(scm.influences), golden["model"]["causal_edges"]["count"]],
        ["Production relations", len(scm.production_relations),
         golden["model"]["production_edges"]["count"]],
        ["Constitutive edges", len(scm.constitutive_constraints),
         golden["model"]["constitutive_edges"]["count"]],
        ["Quantitative definitions", len(scm.quantitative_expressions),
         golden["model"]["quantitative_definitions"]["count"]],
        ["Modulations", len(scm.modulation), golden["model"]["modulation_edges"]["count"]]])
    evidence = stats["causal_evidence"]
    outputs["causal-evidence-review.tex"] = table(["Causal-evidence status", "Count"], [
        ["Controlled", evidence["controlled"]],
        ["Legacy unclassified", evidence["legacy_unclassified"]],
        ["Frozen review baseline", evidence["review_baseline"]],
        ["Human-approved resolutions", evidence["review_approved_resolved"]],
        ["Open review items", evidence["review_open"]]])
    outcomes = report["reasoning_validation"]
    outputs["validation-outcomes.tex"] = table(["Release gate", "Outcome"], [
        ["OWL 2 EL profile", outcomes["owl2_el_profile"]],
        ["ELK consistency", outcomes["elk_consistency"]],
        ["ELK classification", outcomes["elk_classification"]],
        ["Projection equivalence", outcomes["projection_equivalence"]],
        ["Derivative rules", quantitative.exact_rules_checked],
        ["Numerical realizations", quantitative.numerical_trials]])
    outputs["reasoning-performance.tex"] = table(["Source module", "Axioms", "Extraction (s)"], [
        [record["source"].replace("_", "\\_"), record.get("axiom_count", "--"),
         record.get("extraction_seconds", "--")] for record in modules["modules"]])
    outputs["benchmark-outcomes.tex"] = table(
        ["Benchmark", "Cases", "Correct", "Wrong", "Ambiguous"],
        [[name.replace("_", "\\_"), result["cases"], result["correct"], result["wrong"],
          result["ambiguous"]] for name, result in sorted(golden["benchmarks"].items())], "lrrrr")
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifact-dir", type=Path, default=ROOT / "build/migration")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "docs/generated")
    parser.add_argument("--paper-dir", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(args.artifact_dir)
    paper_dir = args.paper_dir or ROOT / "paper/generated"
    directories = [args.output_dir]
    if args.paper_dir is not None or paper_dir.parent.is_dir():
        directories.append(paper_dir)
    if args.check:
        stale = [f"{directory}/{name}" for directory in directories
                 for name, content in expected.items()
                 if not (directory / name).is_file()
                 or (directory / name).read_text(encoding="utf-8") != content]
        if stale:
            raise SystemExit(f"stale generated manuscript artifacts: {', '.join(stale)}")
        print("generated manuscript statistics: current")
        return 0
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
        for name, content in expected.items():
            (directory / name).write_text(content, encoding="utf-8")
    print(f"wrote {', '.join(expected)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
