#!/usr/bin/env python3
"""Verify every ontology IRI in the PhysioMap corpus DIRECTLY against canonical OBO files.

Downloads the source OBO release for each ontology used (PATO, CL, GO, Uberon, ChEBI, PR) to a
local gitignored cache, parses ``id``/``name``/``synonym``/``is_obsolete`` for every term, then
checks every ``entity_iri`` / ``quality_iri`` / ``bearer_entity_iri`` in the fixtures and every
``ontology/partof.yaml`` entry:

  * the ID must EXIST in its ontology (not absent),
  * it must NOT be obsolete,
  * where ``partof.yaml`` asserts a label, it must match the OBO name (or an exact synonym).

Exit 0 = all clean; exit 1 = any not-found / obsolete / label-mismatch (CI-style gate).
Usage:  uv run python scripts/verify_ontology_ids.py [--refresh]
"""

from __future__ import annotations

import re
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "ontology" / ".obo_cache"

# canonical OBO products (the "basic"/"lite" releases carry every term id + name, smaller)
SOURCES = {
    "PATO": "http://purl.obolibrary.org/obo/pato.obo",
    "CL": "http://purl.obolibrary.org/obo/cl/cl-basic.obo",
    "GO": "http://purl.obolibrary.org/obo/go/go-basic.obo",
    "UBERON": "http://purl.obolibrary.org/obo/uberon/uberon-basic.obo",
    "CHEBI": "http://purl.obolibrary.org/obo/chebi/chebi_lite.obo",
    "PR": "http://purl.obolibrary.org/obo/pr.obo",
}
CORPUS_GLOBS = ["benchmarks/**/*.yaml", "ontology/partof.yaml"]
CURIE_LOCAL = r"[A-Za-z0-9][A-Za-z0-9._-]*"
IRI_RE = re.compile(
    rf"(entity_iri|quality_iri|bearer_entity_iri):\s*"
    rf"([A-Za-z][A-Za-z0-9_-]*:{CURIE_LOCAL})"
)

# checked-in manifest of every verified IRI -> canonical OBO label. The offline test
# (tests/test_ontology_ids.py) asserts every corpus IRI is present here; the network test
# re-checks this manifest against the live OBO files. Regenerate with --write-manifest.
MANIFEST = ROOT / "ontology" / "verified_ids.yaml"


def cache_present() -> bool:
    return all((CACHE / f"{pre}.obo").exists() for pre in SOURCES)


def fetch(refresh: bool = False) -> None:
    CACHE.mkdir(parents=True, exist_ok=True)
    for pre, url in SOURCES.items():
        dest = CACHE / f"{pre}.obo"
        if dest.exists() and not refresh:
            continue
        print(f"  downloading {pre} <- {url}", file=sys.stderr)
        urllib.request.urlretrieve(url, dest)


def parse_terms() -> dict[str, dict]:
    terms: dict[str, dict] = {}
    for pre in SOURCES:
        cur = None
        for line in (CACHE / f"{pre}.obo").read_text(encoding="utf-8", errors="replace").splitlines():
            if line == "[Term]":
                cur = None
            elif line.startswith("id: "):
                cur = line[4:].strip()
                terms.setdefault(cur, {"name": None, "syn": set(), "obs": False})
            elif cur:
                if line.startswith("name: "):
                    terms[cur]["name"] = line[6:].strip()
                elif line.startswith("synonym: "):
                    m = re.search(r'"([^"]*)"', line)
                    if m:
                        terms[cur]["syn"].add(m.group(1).lower())
                elif line.startswith("is_obsolete: true"):
                    terms[cur]["obs"] = True
    return terms


def collect_ids() -> tuple[set[str], dict[str, str]]:
    used: set[str] = set()
    asserted: dict[str, str] = {}
    pf = yaml.safe_load((ROOT / "ontology/partof.yaml").read_text()).get("entities", {})
    for iri, rec in pf.items():
        used.add(iri)
        if rec.get("label"):
            asserted[iri] = rec["label"]
    for pat in CORPUS_GLOBS:
        for f in ROOT.glob(pat):
            for line in f.read_text().splitlines():
                m = IRI_RE.search(line)
                if m:
                    used.add(m.group(2))
    return used, asserted


def norm(s: str | None) -> str:
    return re.sub(r"\s+", " ", (s or "").strip().lower())


def write_manifest() -> int:
    """Regenerate ontology/verified_ids.yaml = {IRI: canonical OBO label} for every used ID."""
    fetch(refresh="--refresh" in sys.argv)
    terms = parse_terms()
    used, _ = collect_ids()
    missing = sorted(i for i in used if i not in terms or terms[i]["obs"])
    if missing:
        print(f"refusing to write manifest — {len(missing)} unverifiable IDs: {missing}")
        return 1
    lines = ["# Auto-generated by scripts/verify_ontology_ids.py --write-manifest.",
             "# Every ontology IRI used in the corpus, mapped to its canonical OBO label,",
             "# verified directly against the downloaded OBO release. Do not edit by hand.",
             "ids:"]
    for iri in sorted(used):
        lines.append(f"  {iri}: {terms[iri]['name']!r}")
    MANIFEST.write_text("\n".join(lines) + "\n")
    print(f"wrote {MANIFEST} ({len(used)} IDs)")
    return 0


def main() -> int:
    if "--write-manifest" in sys.argv:
        return write_manifest()
    fetch(refresh="--refresh" in sys.argv)
    terms = parse_terms()
    used, asserted = collect_ids()
    not_found, obsolete, mismatch = [], [], []
    for iri in sorted(used):
        t = terms.get(iri)
        if t is None:
            not_found.append(iri)
            continue
        if t["obs"]:
            obsolete.append((iri, t["name"]))
        lab = asserted.get(iri)
        if lab and norm(lab) != norm(t["name"]) and norm(lab) not in t["syn"]:
            mismatch.append((iri, lab, t["name"]))
    ok = len(used) - len(not_found) - len(mismatch)
    print(f"verified {len(used)} ontology IDs against {len(SOURCES)} OBO files "
          f"({len(terms)} terms parsed)")
    print(f"  OK={ok}  NOT_FOUND={len(not_found)}  OBSOLETE={len(obsolete)}  LABEL_MISMATCH={len(mismatch)}")
    for i in not_found:
        print(f"  NOT_FOUND   {i}")
    for i, n in obsolete:
        print(f"  OBSOLETE    {i} (was: {n})")
    for i, lab, name in mismatch:
        print(f"  MISMATCH    {i}: asserted {lab!r} != OBO {name!r}")
    bad = bool(not_found or obsolete or mismatch)
    print("RESULT:", "FAIL" if bad else "OK")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
